export const CATALOG_PRODUCTS = [
  {
    id: 'demo-soja',
    nome: 'MAP',
    displayNome: 'MAP · Demo',
    quarter: 'Q1',
    precoBase: 1850,
    custoBrl: 1850,
    custoIcms: 1776,
    vencimentoLista: '',
  },
  {
    id: 'demo-milho',
    nome: 'KCl',
    displayNome: 'KCl · Demo',
    quarter: 'Q1',
    precoBase: 1620,
    custoBrl: 1620,
    custoIcms: 1555.2,
    vencimentoLista: '',
  },
  {
    id: 'demo-algodao',
    nome: 'Ureia',
    displayNome: 'Ureia · Demo',
    quarter: 'Q2',
    precoBase: 2100,
    custoBrl: 2100,
    custoIcms: 2016,
    vencimentoLista: '',
  },
]
